import type {Metadata} from "next";
import {Outfit} from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Admin management",
  description: "Generated by ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true"
        className={`${outfit.className} selection:bg-black selection:text-white antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
